### ISSUE TITLE
bug(workspace): nx update fails because npm ci fails because of package.lock.json not in sync

### ISSUE THREAD

**Issue by WolfSoko** [nx-squeezer/squeezer#427]
Hi there again, 

The renovate configuration cannot update angular dependencies because of this error: 

```
npm ci --ignore-scripts\nnpm ERR! code EUSAGE\nnpm ERR! \nnpm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing
```
See here: Actions error here: https://github.com/WolfSoko/nx-renovate-self-hosted/actions/runs/4142808995/jobs/7163919269#step:3:6962

I don't know exactly but maybe a `npm install --ignore-scripts` would be more appropriate than `npm ci --ignore-scripts`? 

Your relevant renovate config lines: 
ref: [nrwlWorkspace.json#L55](https://github.com/nx-squeezer/squeezer/blob/ed408e57bf16f423c60e7251f053de6a8524f886/nrwlWorkspace.json#L55)
ref: [nrwlWorkspace.json#L55](https://github.com/nx-squeezer/squeezer/blob/ed408e57bf16f423c60e7251f053de6a8524f886/nrwlWorkspace.json#L83)

I will try `npm install` in my nx-clean repo.

**Comment by samuelfernandez** [comment]
@WolfSoko Thanks so much for this report. Checking at the logs, this is what I've found:

* First, Renovate updates `@angular/cli`. When it does, `package-lock.json` is correctly updated, that is a feature of Renovate. You can tell it is successful because next command succeeds.
* It runs successfully `npm ci --ignore-scripts` ([logs](https://github.com/WolfSoko/nx-renovate-self-hosted/actions/runs/4142808995/jobs/7163919269#step:3:6832), so the problem is not there.
* The upgrade command modifies `package.json` ([logs](https://github.com/WolfSoko/nx-renovate-self-hosted/actions/runs/4142808995/jobs/7163919269#step:3:6873).
* Next command `nx migrate --run-migrations` mentions that it internally runs `npm install` ([logs](https://github.com/WolfSoko/nx-renovate-self-hosted/actions/runs/4142808995/jobs/7163919269#step:3:6888)). The logs show that `npm install` actually runs, it even runs git hooks:

```shell
Git hooks installed\n\nremoved 557 packages, and audited 1952 packages in 6s
```

* When processing the next dependency, `@angular/cli`, it fails there. So somehow at this point is fails, even though previous processes seem to show it should work.

So, I feel that the first `npm ci` is OK, and should stay as it is, and I don't have at this moment a better understanding of the underlying issue. I'll see if I can replicate this problem locally, which I hope sheds light on the issue.

@WolfSoko If this happens again, please LMK before merging the Renovate PR

**Comment by WolfSoko** [comment]
Thank you very much for the great anaylsis. 

So it looks like a more complicated issue. I tried to use `npm install` and now renovate did run without errors, but the pr CI Pipeline fails with a similar error. 

My other repo had no problem with the update afaik.

**Comment by samuelfernandez** [comment]
I've just cloned `nx-clean`, and followed the upgrade commands manually. I have confirmed that right after running `nx migrate --run-migrations`, if I tried to run `npm ci` it throws the same error as in your Renovate logs. Somehow, when `x migrate --run-migrations` runs internally `npm install`, it does not work well. It is one of those curious things, because the docs say that you should run it manually, but the tool runs it anyway.

Nevertheless, I think the solution would be adding `npm install` between step 3 and step 4, as `nx` suggests. I'll try to update that into the default config.

**Comment by WolfSoko** [comment]
@samuelfernandez thank you very much for debugging my repo! Awesome!
